### ISSUE TITLE
Awesome backbones 训练的模型如何在移动端使用?

### ISSUE THREAD

**Issue by yao-th** [Fafa-DL/Awesome-Backbones#130]
我用torch.jit.trace() export 模型的时候报错, 之前也有人遇到同样的问题. 不知道如何解决? 或者有其他的方法让AB输出的模型在移动端上使用么?

(torch) E:\python\Awesome-Backbones>python tools/pth2pt.py models\repvgg\repvgg_A0.py
Loading Train_Epoch042-Loss0.012.pth

Traceback (most recent call last):
File "tools/pth2pt.py", line 125, in
main()
File "tools/pth2pt.py", line 121, in main
traced_script_module = torch.jit.trace(model, example)
File "D:\anaconda3\envs\torch\lib\site-packages\torch\jit_trace.py", line 742, in trace
_module_class,
File "D:\anaconda3\envs\torch\lib\site-packages\torch\jit_trace.py", line 940, in trace_module
_force_outplace,
File "D:\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 725, in _call_impl
result = self._slow_forward(*input, **kwargs)
File "D:\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 709, in _slow_forward
result = self.forward(*input, **kwargs)
File "E:\python\Awesome-Backbones\models\build.py", line 125, in forward
return self.forward_train(x,**kwargs)
TypeError: forward_train() missing 1 required positional argument: 'targets'

**Comment by Fafa-DL** [comment]
这里应该不能调用forward_train

**Comment by PurpleSky-NS** [comment]
给模型传参数的时候，多传两个False就会走forward_test了，参考导出onnx
#68

**Comment by Fafa-DL** [comment]
> 给模型传参数的时候，多传两个False就会走forward_test了，参考导出onnx #68

可以将这个特性合入进来~

**Comment by PurpleSky-NS** [comment]
> > 给模型传参数的时候，多传两个False就会走forward_test了，参考导出onnx [#68](https://github.com/Fafa-DL/Awesome-Backbones/issues/68)
> 
> 可以将这个特性合入进来，提个PR吧

之前已经提交PR了(#136 )，我导出的mobilenet在我的设备上可以正常工作:)

**Comment by lifw555** [comment]
> > > 给模型传参数的时候，多传两个False就会走forward_test了，参考导出onnx [#68](https://github.com/Fafa-DL/Awesome-Backbones/issues/68)
> > 
> > 
> > 可以将这个特性合入进来，提个PR吧
> 
> 之前已经提交PR了([#136](https://github.com/Fafa-DL/Awesome-Backbones/pull/136) )，我导出的mobilenet在我的设备上可以正常工作:)

我导出EfficientNetV2模型的报错，@PurpleSky-NS 您看下可能的问题#142

**Comment by Maplexff** [comment]
运行脚本python tools/export_onnx.py models/efficientnetv2/efficientnetv2_m.py --checkpoint logs/EfficientNetV2/2025-04-06-19-59-56/Val_Epoch229-Acc98.525.pth提示报错RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type bool是什么原因
