### ISSUE TITLE
训练和评估都提示报错，求助

### ISSUE THREAD

**Issue by Abidalswark** [Fafa-DL/Awesome-Backbones#134]
Traceback (most recent call last):
  File "D:\project\Awesome-Backbones\tools\batch_test.py", line 61, in <module>
    main()
  File "D:\project\Awesome-Backbones\tools\batch_test.py", line 48, in main
    img_show = imshow_infos(img, result,show = False,out_file=out_path)
  File "D:\project\Awesome-Backbones\core\visualization\image.py", line 334, in imshow_infos
    _, img = manager.put_img_infos(
  File "D:\project\Awesome-Backbones\core\visualization\image.py", line 269, in put_img_infos
    stream, _ = self.fig_save.canvas.print_to_buffer()
  File "D:\anaconda3\envs\Image_classification\lib\site-packages\matplotlib\backends\backend_agg.py", line 499, in print_to_buffer
    FigureCanvasAgg.draw(self)
  File "D:\anaconda3\envs\Image_classification\lib\site-packages\matplotlib\backends\backend_agg.py", line 387, in draw
    self.figure.draw(self.renderer)
  File "D:\anaconda3\envs\Image_classification\lib\site-packages\matplotlib\artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "D:\anaconda3\envs\Image_classification\lib\site-packages\matplotlib\artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "D:\anaconda3\envs\Image_classification\lib\site-packages\matplotlib\figure.py", line 3162, in draw
    mimage._draw_list_compositing_images(
  File "D:\anaconda3\envs\Image_classification\lib\site-packages\matplotlib\image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "D:\anaconda3\envs\Image_classification\lib\site-packages\matplotlib\artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "D:\anaconda3\envs\Image_classification\lib\site-packages\matplotlib\axes\_base.py", line 3137, in draw
    mimage._draw_list_compositing_images(
  File "D:\anaconda3\envs\Image_classification\lib\site-packages\matplotlib\image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "D:\anaconda3\envs\Image_classification\lib\site-packages\matplotlib\artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "D:\anaconda3\envs\Image_classification\lib\site-packages\matplotlib\image.py", line 656, in draw
    renderer.draw_image(gc, l, b, im)
ValueError: object __array__ method not producing an array

**Comment by Fafa-DL** [comment]
你单帧测试能跑通吗？
