### ISSUE TITLE
训练Deit3出错

### ISSUE THREAD

**Issue by Abidalswark** [Fafa-DL/Awesome-Backbones#139]
Initialize the weights.
Traceback (most recent call last):
  File "/root/Awesome-Backbones/core/datasets/build.py", line 68, in build_from_cfg
    return obj_cls(**args)
TypeError: RandomResizedCrop.__init__() missing 1 required positional argument: 'size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Awesome-Backbones/./tools/train.py", line 170, in <module>
    main()
  File "/root/Awesome-Backbones/./tools/train.py", line 120, in main
    train_dataset = Mydataset(train_datas, train_pipeline)
  File "/root/Awesome-Backbones/utils/dataloader.py", line 16, in __init__
    self.pipeline = Compose(self.cfg)
  File "/root/Awesome-Backbones/core/datasets/compose.py", line 23, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/root/Awesome-Backbones/core/datasets/build.py", line 71, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: RandomResizedCrop: RandomResizedCrop.__init__() missing 1 required positional argument: 'size'

**Comment by Fafa-DL** [comment]
跑其他的模型OK吗？

**Comment by Abidalswark** [comment]
OK的，最近跑的davit是没问题的
