### ISSUE TITLE
not registry

### ISSUE THREAD

**Issue by yly001** [Fafa-DL/Awesome-Backbones#14]
(pytorch-gpu) C:\ai-project\Awesome-Backbones-main>python tools/evaluation.py models/shufflenet/shufflenet_v2.py
tools/evaluation.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Loading Val_Epoch001-Acc100.000.pth
<All keys matched successfully>
Traceback (most recent call last):
  File "tools/evaluation.py", line 169, in <module>
    main()
  File "tools/evaluation.py", line 146, in main
    test_dataset = Mydataset(test_datas, val_pipeline)
  File "C:\ai-project\Awesome-Backbones-main\utils\dataloader.py", line 16, in __init__
    self.pipeline = Compose(self.cfg)
  File "C:\ai-project\Awesome-Backbones-main\core\datasets\compose.py", line 23, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "C:\ai-project\Awesome-Backbones-main\core\datasets\build.py", line 61, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'RandomHorizontalFlip is not in the pipeline registry'

**Comment by Fafa-DL** [comment]
看这个报错是因为配置文件还是上一个版本而数据处理代码用的最新版本，你可以版本统一下。
