### ISSUE TITLE
训练得到的pth文件，想在C++环境下调用模型，libtorch要求先转化模型，在使用torch.jit.trace(model, example)时报错

### ISSUE THREAD

**Issue by zhigangjun** [Fafa-DL/Awesome-Backbones#40]
报错如下：
(torch) E:\python\Awesome-Backbones>python tools/pth2pt.py models\repvgg\repvgg_A0.py
Loading Train_Epoch042-Loss0.012.pth
<All keys matched successfully>
Traceback (most recent call last):
  File "tools/pth2pt.py", line 125, in <module>
    main()
  File "tools/pth2pt.py", line 121, in main
    traced_script_module = torch.jit.trace(model, example)
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\jit\_trace.py", line 742, in trace
    _module_class,
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\jit\_trace.py", line 940, in trace_module
    _force_outplace,
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "E:\python\Awesome-Backbones\models\build.py", line 125, in forward
    return self.forward_train(x,**kwargs)
TypeError: forward_train() missing 1 required positional argument: 'targets'

请问博主有做这方面的工作不，期待您的回复

**Comment by Fafa-DL** [comment]
不好意思啊暂时未涉及到该方面

**Comment by yao-th** [comment]
我也遇到了相同的问题, 用Awesome backbones训练的模型怎么在移动端上使用呢?
