### ISSUE TITLE
训练mobilenet_v3_small时报错

### ISSUE THREAD

**Issue by 875591584** [Fafa-DL/Awesome-Backbones#59]
Train: Epoch 1/100:   0%|                                                                               | 0/804 [00:00<?, ?it/s<class 'dict'>]
Traceback (most recent call last):
  File "tools/train.py", line 170, in <module>
    main()
  File "tools/train.py", line 164, in main
    train(model,runner, lr_update_func, device, epoch, data_cfg.get('train').get('epoches'), meta)
  File "/lvhuiyong/Classification/Classification/awesome-backbones-main/utils/train_utils.py", line 207, in train
    for iter, batch in enumerate(runner.get('train_loader')):            
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/lvhuiyong/Classification/Classification/awesome-backbones-main/utils/dataloader.py", line 43, in __getitem__
    results = self.pipeline(copy.deepcopy(self.data_infos[index]))
  File "/lvhuiyong/Classification/Classification/awesome-backbones-main/core/datasets/compose.py", line 33, in __call__
    data = t(data)
  File "/lvhuiyong/Classification/Classification/awesome-backbones-main/core/datasets/loading.py", line 55, in __call__
    img_bytes = self.get(filename)
  File "/lvhuiyong/Classification/Classification/awesome-backbones-main/core/datasets/loading.py", line 44, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets\\train\\late_blight\\late_blight3315.jpg'

**Comment by 875591584** [comment]
在本地终端好像可以 为什么在云服务器上不行

**Comment by 875591584** [comment]
在本地终端好像可以 为什么在云服务器上不行

**Comment by jcdasheng** [comment]
怎么解决

**Comment by 875591584** [comment]
没有 你也遇到了吗  解决了吗

**Comment by Fafa-DL** [comment]
服务器不都是载入的docker吗？如果本地代码能跑建议去检查环境问题

**Comment by Fafa-DL** [comment]
> 没有 你也遇到了吗 解决了吗

你这个报错明显是没找到`datasets\train\late_blight\late_blight3315.jpg`这个文件
