### ISSUE TITLE
测试单张图片时报错

### ISSUE THREAD

**Issue by HY-222** [Fafa-DL/Awesome-Backbones#70]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by HY-222** [comment]
> 首页快速开始的demo能跑出来吗

可以，运行tinyvit_5m.py这个脚本的时候报的错

**Comment by HY-222** [comment]
完整报错是这样的
Traceback (most recent call last):
  File "tools/single_test.py", line 42, in <module>
    main()
  File "tools/single_test.py", line 36, in main
    result = inference_model(model, args.img, val_pipeline, classes_names,label_names)
  File "/home/work/hy/data_clean/task/Awesome-Backbones-main/utils/inference.py", line 63, in inference_model
    scores = model(image.to(device),return_loss=False)
  File "/home/work/.conda/envs/control/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/hy/data_clean/task/Awesome-Backbones-main/models/build.py", line 127, in forward
    return self.forward_test(x,**kwargs)
  File "/home/work/hy/data_clean/task/Awesome-Backbones-main/models/build.py", line 138, in forward_test
    x = self.extract_feat(x)
  File "/home/work/hy/data_clean/task/Awesome-Backbones-main/models/build.py", line 113, in extract_feat
    x = self.backbone(img)
  File "/home/work/.conda/envs/control/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/hy/data_clean/task/Awesome-Backbones-main/configs/backbones/tinyvit.py", line 742, in forward
    x = stage(x)
  File "/home/work/.conda/envs/control/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/hy/data_clean/task/Awesome-Backbones-main/configs/backbones/tinyvit.py", line 552, in forward
    x = block(x)
  File "/home/work/.conda/envs/control/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/hy/data_clean/task/Awesome-Backbones-main/configs/backbones/tinyvit.py", line 457, in forward
    x = self.attn(x)
  File "/home/work/.conda/envs/control/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/hy/data_clean/task/Awesome-Backbones-main/configs/common/attention.py", line 803, in forward
    attn = ((q @ k.transpose(-2, -1)) * self.scale +
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by Fafa-DL** [comment]
不好意思这段时间太忙了，你调用评估工具时会报错吗？我理解如果批量评估没问题那单张肯定没事。
