### ISSUE TITLE
测试单张图片时报错: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

### ISSUE THREAD

**Issue by whitewatercn** [Fafa-DL/Awesome-Backbones#77]
测试单张图片时报错 
```
! python tools/single_test.py /Users/whitewatercn/FennecNas/coding/zhongyaoxianwei/黄褐毛忍冬_10X_DM500_test/0006.jpg models/swin_transformer_v2/small_256.py
```

报错内容
```python
/Users/whitewatercn/miniconda3/envs/torch/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Loading Train_Epoch089.pth
Traceback (most recent call last):
  File "tools/single_test.py", line 42, in <module>
    main()
  File "tools/single_test.py", line 33, in main
    model = init_model(model, data_cfg, device=device, mode='eval')
  File "/Users/whitewatercn/FennecNas/coding/zhongyaoxianwei/AwesomeBackbones/utils/inference.py", line 27, in init_model
    load_checkpoint(model,data_cfg.get('test').get('ckpt'),device,False)
  File "/Users/whitewatercn/FennecNas/coding/zhongyaoxianwei/AwesomeBackbones/utils/checkpoint.py", line 217, in load_checkpoint
    checkpoint = torch.load(filename, map_location)
  File "/Users/whitewatercn/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/whitewatercn/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/Users/whitewatercn/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/Users/whitewatercn/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/Users/whitewatercn/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 1086, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/Users/whitewatercn/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "/Users/whitewatercn/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/Users/whitewatercn/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by whitewatercn** [comment]
将`tools/single_test.py`中的
```
    parser.add_argument(
        '--device', default='cuda', help='Device used for inference')
```

手动改为
```
    parser.add_argument(
        # '--device', default='cuda', help='Device used for inference')
        '--device', default='cpu', help='Device used for inference')
```

即可

期待up加一个自动识别功能，我看不太懂，只能做到这里了

<img width="1214" alt="image" src="https://github.com/Fafa-DL/Awesome-Backbones/assets/58654928/4dd54b8f-176e-48a9-b44e-592afdc450a0">

**Comment by Fafa-DL** [comment]
其实是有这个逻辑的，可以看截图代码29-32行，不过现在看来没生效，因为args.device无论在终端是否指定（未指定默认为cuda）都为True，感谢反馈
