### ISSUE TITLE
请问这个报错：AttributeError: 'EfficientFormerClsHead' object has no attribute 'post_process'，没有post_process()方法？

### ISSUE THREAD

**Issue by couleur123123** [Fafa-DL/Awesome-Backbones#93]

**Comment by Fafa-DL** [comment]
报错信息帖完整~

**Comment by couleur123123** [comment]
Train: Epoch 1/100:   0%|          | 0/651 [00:15<?, ?it/s<class 'dict'>]
Traceback (most recent call last):
  File "D:\PyProj\Learn\Awesome-Backbones-main\utils\train_utils.py", line 221, in train
    preds, losses = model(images, targets=targets, return_loss=True, train_statu=True)
  File "E:\SoftwareInstall\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\SoftwareInstall\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\SoftwareInstall\Anaconda\envs\pytorch\lib\site-packages\torch\nn\parallel\data_parallel.py", line 183, in forward
    return self.module(*inputs[0], **module_kwargs[0])
  File "E:\SoftwareInstall\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\SoftwareInstall\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\PyProj\Learn\Awesome-Backbones-main\models\build.py", line 132, in forward
    return self.forward_test(x), self.forward_train(x, **kwargs)
  File "D:\PyProj\Learn\Awesome-Backbones-main\models\build.py", line 143, in forward_test
    out = self.head.simple_test(x, **kwargs)
  File "D:\PyProj\Learn\Awesome-Backbones-main\configs\heads\efficientformer_head.py", line 81, in simple_test
    return self.post_process(pred)
  File "E:\SoftwareInstall\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'EfficientFormerClsHead' object has no attribute 'post_process'

**Comment by Fafa-DL** [comment]
> 请问为什么一开始模型就匹配不上？

因为你的分类是4类而预训练模型是1000类，分类头肯定是不匹配的，可以理解为此处加载预训练模型更多的用他的backbone而重训分类头

**Comment by couleur123123** [comment]
刚开始接触不太明白，请问一下我尝试其他模型的时候用LinearClsHead这个分类头，我numclass也是直接改成4的，为什么这个分类头是可以直接匹配的？

**Comment by Fafa-DL** [comment]
> 刚开始接触不太明白，请问一下我尝试其他模型的时候用LinearClsHead这个分类头，我numclass也是直接改成4的，为什么这个分类头是可以直接匹配的？

你改了结构当然权重匹配不上啊
