### ISSUE TITLE
加入新的主干运行后出现Initialize the weights. Traceback (most recent call last):   File "tools/train.py", line 171, in <module>     main()   File "tools/train.py", line 136, in main     max_iters         = data_cfg.get('train').get('epoches')*len(train_loader), TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'的问题怎么解决

### ISSUE THREAD

**Issue by pdqdw** [Fafa-DL/Awesome-Backbones#99]
![1712904622585](https://github.com/Fafa-DL/Awesome-Backbones/assets/166367842/f9b89cbf-3858-4c0e-be15-9dce0e7d93d0)

**Comment by Fafa-DL** [comment]
描述不清晰啊
